export const odynitiveFactoryAbi = [
  { type:'function', name:'marketCount', stateMutability:'view', inputs:[], outputs:[{type:'uint256'}] },
  { type:'function', name:'getMarkets', stateMutability:'view', inputs:[{name:'offset',type:'uint256'},{name:'limit',type:'uint256'}], outputs:[{name:'markets',type:'tuple[]',components:[{name:'token',type:'address'},{name:'creator',type:'address'},{name:'name',type:'string'},{name:'symbol',type:'string'},{name:'description',type:'string'},{name:'imageURI',type:'string'},{name:'website',type:'string'},{name:'socialLink',type:'string'},{name:'virtualRitualReserve',type:'uint256'},{name:'virtualTokenReserve',type:'uint256'},{name:'realRitualReserve',type:'uint256'},{name:'tokensSold',type:'uint256'},{name:'totalVolume',type:'uint256'},{name:'createdAt',type:'uint256'},{name:'tradeCount',type:'uint256'},{name:'active',type:'bool'}]}] },
  { type:'function', name:'getMarket', stateMutability:'view', inputs:[{name:'token',type:'address'}], outputs:[{name:'market',type:'tuple',components:[{name:'token',type:'address'},{name:'creator',type:'address'},{name:'name',type:'string'},{name:'symbol',type:'string'},{name:'description',type:'string'},{name:'imageURI',type:'string'},{name:'website',type:'string'},{name:'socialLink',type:'string'},{name:'virtualRitualReserve',type:'uint256'},{name:'virtualTokenReserve',type:'uint256'},{name:'realRitualReserve',type:'uint256'},{name:'tokensSold',type:'uint256'},{name:'totalVolume',type:'uint256'},{name:'createdAt',type:'uint256'},{name:'tradeCount',type:'uint256'},{name:'active',type:'bool'}]}] },
  { type:'function', name:'quoteBuy', stateMutability:'view', inputs:[{name:'token',type:'address'},{name:'nativeIn',type:'uint256'}], outputs:[{name:'tokenOut',type:'uint256'},{name:'protocolFee',type:'uint256'},{name:'creatorFee',type:'uint256'}] },
  { type:'function', name:'quoteSell', stateMutability:'view', inputs:[{name:'token',type:'address'},{name:'tokenIn',type:'uint256'}], outputs:[{name:'nativeOut',type:'uint256'},{name:'protocolFee',type:'uint256'},{name:'creatorFee',type:'uint256'}] },
  { type:'function', name:'launchToken', stateMutability:'nonpayable', inputs:[{name:'name',type:'string'},{name:'symbol',type:'string'},{name:'description',type:'string'},{name:'imageURI',type:'string'},{name:'website',type:'string'},{name:'socialLink',type:'string'}], outputs:[{name:'token',type:'address'}] },
  { type:'function', name:'buy', stateMutability:'payable', inputs:[{name:'token',type:'address'},{name:'minTokensOut',type:'uint256'}], outputs:[{name:'tokenOut',type:'uint256'}] },
  { type:'function', name:'sell', stateMutability:'nonpayable', inputs:[{name:'token',type:'address'},{name:'tokenIn',type:'uint256'},{name:'minNativeOut',type:'uint256'}], outputs:[{name:'nativeOut',type:'uint256'}] },
  { type:'event', name:'TokenLaunched', anonymous:false, inputs:[{name:'token',type:'address',indexed:true},{name:'creator',type:'address',indexed:true},{name:'name',type:'string',indexed:false},{name:'symbol',type:'string',indexed:false},{name:'marketIndex',type:'uint256',indexed:true}] }
] as const

export const erc20Abi = [
  { type:'function', name:'balanceOf', stateMutability:'view', inputs:[{name:'account',type:'address'}], outputs:[{type:'uint256'}] },
  { type:'function', name:'allowance', stateMutability:'view', inputs:[{name:'owner',type:'address'},{name:'spender',type:'address'}], outputs:[{type:'uint256'}] },
  { type:'function', name:'approve', stateMutability:'nonpayable', inputs:[{name:'spender',type:'address'},{name:'amount',type:'uint256'}], outputs:[{type:'bool'}] },
] as const
