/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace OdynitiveFactory {
  export type MarketStruct = {
    token: AddressLike;
    creator: AddressLike;
    name: string;
    symbol: string;
    description: string;
    imageURI: string;
    website: string;
    social: string;
    virtualRitualReserve: BigNumberish;
    virtualTokenReserve: BigNumberish;
    realRitualReserve: BigNumberish;
    tokensSold: BigNumberish;
    totalVolume: BigNumberish;
    createdAt: BigNumberish;
    tradeCount: BigNumberish;
    active: boolean;
  };

  export type MarketStructOutput = [
    token: string,
    creator: string,
    name: string,
    symbol: string,
    description: string,
    imageURI: string,
    website: string,
    social: string,
    virtualRitualReserve: bigint,
    virtualTokenReserve: bigint,
    realRitualReserve: bigint,
    tokensSold: bigint,
    totalVolume: bigint,
    createdAt: bigint,
    tradeCount: bigint,
    active: boolean
  ] & {
    token: string;
    creator: string;
    name: string;
    symbol: string;
    description: string;
    imageURI: string;
    website: string;
    social: string;
    virtualRitualReserve: bigint;
    virtualTokenReserve: bigint;
    realRitualReserve: bigint;
    tokensSold: bigint;
    totalVolume: bigint;
    createdAt: bigint;
    tradeCount: bigint;
    active: boolean;
  };
}

export interface OdynitiveFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOMINATOR"
      | "BUILDER"
      | "BUILDER_ADDRESS"
      | "INITIAL_VIRTUAL_NATIVE_RESERVE"
      | "INITIAL_VIRTUAL_TOKEN_RESERVE"
      | "MAX_PAGE_SIZE"
      | "MAX_TOTAL_FEE_BPS"
      | "TOKEN_SUPPLY"
      | "buy"
      | "creatorFeeBps"
      | "creatorFeesAccrued"
      | "getMarket"
      | "getMarkets"
      | "launchToken"
      | "marketAt"
      | "marketCount"
      | "owner"
      | "protocolFeeBps"
      | "protocolFeesAccrued"
      | "protocolTreasury"
      | "quoteBuy"
      | "quoteSell"
      | "sell"
      | "setFees"
      | "setProtocolTreasury"
      | "transferOwnership"
      | "withdrawCreatorFees"
      | "withdrawProtocolFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CreatorFeesWithdrawn"
      | "FeesUpdated"
      | "OwnershipTransferred"
      | "ProtocolFeesWithdrawn"
      | "ProtocolTreasuryUpdated"
      | "TokenLaunched"
      | "TokensBought"
      | "TokensSold"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "BUILDER", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "BUILDER_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INITIAL_VIRTUAL_NATIVE_RESERVE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INITIAL_VIRTUAL_TOKEN_RESERVE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_PAGE_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_TOTAL_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOKEN_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buy",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "creatorFeesAccrued",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarket",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarkets",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "launchToken",
    values: [string, string, string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "marketAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "marketCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolFeesAccrued",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "quoteBuy",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteSell",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sell",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFees",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawCreatorFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawProtocolFees",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BPS_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "BUILDER", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "BUILDER_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INITIAL_VIRTUAL_NATIVE_RESERVE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INITIAL_VIRTUAL_TOKEN_RESERVE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_PAGE_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_TOTAL_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOKEN_SUPPLY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "creatorFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorFeesAccrued",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMarket", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMarkets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "launchToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "marketAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "marketCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeesAccrued",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "quoteBuy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "quoteSell", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sell", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setFees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawCreatorFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawProtocolFees",
    data: BytesLike
  ): Result;
}

export namespace CreatorFeesWithdrawnEvent {
  export type InputTuple = [creator: AddressLike, amount: BigNumberish];
  export type OutputTuple = [creator: string, amount: bigint];
  export interface OutputObject {
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesUpdatedEvent {
  export type InputTuple = [
    oldProtocolFeeBps: BigNumberish,
    oldCreatorFeeBps: BigNumberish,
    newProtocolFeeBps: BigNumberish,
    newCreatorFeeBps: BigNumberish
  ];
  export type OutputTuple = [
    oldProtocolFeeBps: bigint,
    oldCreatorFeeBps: bigint,
    newProtocolFeeBps: bigint,
    newCreatorFeeBps: bigint
  ];
  export interface OutputObject {
    oldProtocolFeeBps: bigint;
    oldCreatorFeeBps: bigint;
    newProtocolFeeBps: bigint;
    newCreatorFeeBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [oldOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [oldOwner: string, newOwner: string];
  export interface OutputObject {
    oldOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolFeesWithdrawnEvent {
  export type InputTuple = [treasury: AddressLike, amount: BigNumberish];
  export type OutputTuple = [treasury: string, amount: bigint];
  export interface OutputObject {
    treasury: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolTreasuryUpdatedEvent {
  export type InputTuple = [oldTreasury: AddressLike, newTreasury: AddressLike];
  export type OutputTuple = [oldTreasury: string, newTreasury: string];
  export interface OutputObject {
    oldTreasury: string;
    newTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenLaunchedEvent {
  export type InputTuple = [
    token: AddressLike,
    creator: AddressLike,
    name: string,
    symbol: string,
    marketIndex: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    creator: string,
    name: string,
    symbol: string,
    marketIndex: bigint
  ];
  export interface OutputObject {
    token: string;
    creator: string;
    name: string;
    symbol: string;
    marketIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensBoughtEvent {
  export type InputTuple = [
    token: AddressLike,
    buyer: AddressLike,
    nativeIn: BigNumberish,
    tokenOut: BigNumberish,
    protocolFee: BigNumberish,
    creatorFee: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    buyer: string,
    nativeIn: bigint,
    tokenOut: bigint,
    protocolFee: bigint,
    creatorFee: bigint
  ];
  export interface OutputObject {
    token: string;
    buyer: string;
    nativeIn: bigint;
    tokenOut: bigint;
    protocolFee: bigint;
    creatorFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensSoldEvent {
  export type InputTuple = [
    token: AddressLike,
    seller: AddressLike,
    tokenIn: BigNumberish,
    nativeOut: BigNumberish,
    protocolFee: BigNumberish,
    creatorFee: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    seller: string,
    tokenIn: bigint,
    nativeOut: bigint,
    protocolFee: bigint,
    creatorFee: bigint
  ];
  export interface OutputObject {
    token: string;
    seller: string;
    tokenIn: bigint;
    nativeOut: bigint;
    protocolFee: bigint;
    creatorFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OdynitiveFactory extends BaseContract {
  connect(runner?: ContractRunner | null): OdynitiveFactory;
  waitForDeployment(): Promise<this>;

  interface: OdynitiveFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  BUILDER: TypedContractMethod<[], [string], "view">;

  BUILDER_ADDRESS: TypedContractMethod<[], [string], "view">;

  INITIAL_VIRTUAL_NATIVE_RESERVE: TypedContractMethod<[], [bigint], "view">;

  INITIAL_VIRTUAL_TOKEN_RESERVE: TypedContractMethod<[], [bigint], "view">;

  MAX_PAGE_SIZE: TypedContractMethod<[], [bigint], "view">;

  MAX_TOTAL_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  TOKEN_SUPPLY: TypedContractMethod<[], [bigint], "view">;

  buy: TypedContractMethod<
    [token: AddressLike, minTokensOut: BigNumberish],
    [bigint],
    "payable"
  >;

  creatorFeeBps: TypedContractMethod<[], [bigint], "view">;

  creatorFeesAccrued: TypedContractMethod<
    [creator: AddressLike],
    [bigint],
    "view"
  >;

  getMarket: TypedContractMethod<
    [token: AddressLike],
    [OdynitiveFactory.MarketStructOutput],
    "view"
  >;

  getMarkets: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [OdynitiveFactory.MarketStructOutput[]],
    "view"
  >;

  launchToken: TypedContractMethod<
    [
      name: string,
      symbol: string,
      description: string,
      imageURI: string,
      website: string,
      socialLink: string
    ],
    [string],
    "nonpayable"
  >;

  marketAt: TypedContractMethod<[index: BigNumberish], [string], "view">;

  marketCount: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  protocolFeeBps: TypedContractMethod<[], [bigint], "view">;

  protocolFeesAccrued: TypedContractMethod<[], [bigint], "view">;

  protocolTreasury: TypedContractMethod<[], [string], "view">;

  quoteBuy: TypedContractMethod<
    [token: AddressLike, nativeIn: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        tokenOut: bigint;
        protocolFee: bigint;
        creatorFee: bigint;
      }
    ],
    "view"
  >;

  quoteSell: TypedContractMethod<
    [token: AddressLike, tokenIn: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        nativeOut: bigint;
        protocolFee: bigint;
        creatorFee: bigint;
      }
    ],
    "view"
  >;

  sell: TypedContractMethod<
    [token: AddressLike, tokenIn: BigNumberish, minNativeOut: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  setFees: TypedContractMethod<
    [newProtocolFeeBps: BigNumberish, newCreatorFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setProtocolTreasury: TypedContractMethod<
    [newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawCreatorFees: TypedContractMethod<[], [void], "nonpayable">;

  withdrawProtocolFees: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BUILDER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "BUILDER_ADDRESS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INITIAL_VIRTUAL_NATIVE_RESERVE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INITIAL_VIRTUAL_TOKEN_RESERVE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_PAGE_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_TOTAL_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOKEN_SUPPLY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "buy"
  ): TypedContractMethod<
    [token: AddressLike, minTokensOut: BigNumberish],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "creatorFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "creatorFeesAccrued"
  ): TypedContractMethod<[creator: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMarket"
  ): TypedContractMethod<
    [token: AddressLike],
    [OdynitiveFactory.MarketStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMarkets"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [OdynitiveFactory.MarketStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "launchToken"
  ): TypedContractMethod<
    [
      name: string,
      symbol: string,
      description: string,
      imageURI: string,
      website: string,
      socialLink: string
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "marketAt"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "marketCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "protocolFeesAccrued"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "protocolTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "quoteBuy"
  ): TypedContractMethod<
    [token: AddressLike, nativeIn: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        tokenOut: bigint;
        protocolFee: bigint;
        creatorFee: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "quoteSell"
  ): TypedContractMethod<
    [token: AddressLike, tokenIn: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        nativeOut: bigint;
        protocolFee: bigint;
        creatorFee: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "sell"
  ): TypedContractMethod<
    [token: AddressLike, tokenIn: BigNumberish, minNativeOut: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFees"
  ): TypedContractMethod<
    [newProtocolFeeBps: BigNumberish, newCreatorFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setProtocolTreasury"
  ): TypedContractMethod<[newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawCreatorFees"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawProtocolFees"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "CreatorFeesWithdrawn"
  ): TypedContractEvent<
    CreatorFeesWithdrawnEvent.InputTuple,
    CreatorFeesWithdrawnEvent.OutputTuple,
    CreatorFeesWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "FeesUpdated"
  ): TypedContractEvent<
    FeesUpdatedEvent.InputTuple,
    FeesUpdatedEvent.OutputTuple,
    FeesUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolFeesWithdrawn"
  ): TypedContractEvent<
    ProtocolFeesWithdrawnEvent.InputTuple,
    ProtocolFeesWithdrawnEvent.OutputTuple,
    ProtocolFeesWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolTreasuryUpdated"
  ): TypedContractEvent<
    ProtocolTreasuryUpdatedEvent.InputTuple,
    ProtocolTreasuryUpdatedEvent.OutputTuple,
    ProtocolTreasuryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TokenLaunched"
  ): TypedContractEvent<
    TokenLaunchedEvent.InputTuple,
    TokenLaunchedEvent.OutputTuple,
    TokenLaunchedEvent.OutputObject
  >;
  getEvent(
    key: "TokensBought"
  ): TypedContractEvent<
    TokensBoughtEvent.InputTuple,
    TokensBoughtEvent.OutputTuple,
    TokensBoughtEvent.OutputObject
  >;
  getEvent(
    key: "TokensSold"
  ): TypedContractEvent<
    TokensSoldEvent.InputTuple,
    TokensSoldEvent.OutputTuple,
    TokensSoldEvent.OutputObject
  >;

  filters: {
    "CreatorFeesWithdrawn(address,uint256)": TypedContractEvent<
      CreatorFeesWithdrawnEvent.InputTuple,
      CreatorFeesWithdrawnEvent.OutputTuple,
      CreatorFeesWithdrawnEvent.OutputObject
    >;
    CreatorFeesWithdrawn: TypedContractEvent<
      CreatorFeesWithdrawnEvent.InputTuple,
      CreatorFeesWithdrawnEvent.OutputTuple,
      CreatorFeesWithdrawnEvent.OutputObject
    >;

    "FeesUpdated(uint16,uint16,uint16,uint16)": TypedContractEvent<
      FeesUpdatedEvent.InputTuple,
      FeesUpdatedEvent.OutputTuple,
      FeesUpdatedEvent.OutputObject
    >;
    FeesUpdated: TypedContractEvent<
      FeesUpdatedEvent.InputTuple,
      FeesUpdatedEvent.OutputTuple,
      FeesUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProtocolFeesWithdrawn(address,uint256)": TypedContractEvent<
      ProtocolFeesWithdrawnEvent.InputTuple,
      ProtocolFeesWithdrawnEvent.OutputTuple,
      ProtocolFeesWithdrawnEvent.OutputObject
    >;
    ProtocolFeesWithdrawn: TypedContractEvent<
      ProtocolFeesWithdrawnEvent.InputTuple,
      ProtocolFeesWithdrawnEvent.OutputTuple,
      ProtocolFeesWithdrawnEvent.OutputObject
    >;

    "ProtocolTreasuryUpdated(address,address)": TypedContractEvent<
      ProtocolTreasuryUpdatedEvent.InputTuple,
      ProtocolTreasuryUpdatedEvent.OutputTuple,
      ProtocolTreasuryUpdatedEvent.OutputObject
    >;
    ProtocolTreasuryUpdated: TypedContractEvent<
      ProtocolTreasuryUpdatedEvent.InputTuple,
      ProtocolTreasuryUpdatedEvent.OutputTuple,
      ProtocolTreasuryUpdatedEvent.OutputObject
    >;

    "TokenLaunched(address,address,string,string,uint256)": TypedContractEvent<
      TokenLaunchedEvent.InputTuple,
      TokenLaunchedEvent.OutputTuple,
      TokenLaunchedEvent.OutputObject
    >;
    TokenLaunched: TypedContractEvent<
      TokenLaunchedEvent.InputTuple,
      TokenLaunchedEvent.OutputTuple,
      TokenLaunchedEvent.OutputObject
    >;

    "TokensBought(address,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      TokensBoughtEvent.InputTuple,
      TokensBoughtEvent.OutputTuple,
      TokensBoughtEvent.OutputObject
    >;
    TokensBought: TypedContractEvent<
      TokensBoughtEvent.InputTuple,
      TokensBoughtEvent.OutputTuple,
      TokensBoughtEvent.OutputObject
    >;

    "TokensSold(address,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      TokensSoldEvent.InputTuple,
      TokensSoldEvent.OutputTuple,
      TokensSoldEvent.OutputObject
    >;
    TokensSold: TypedContractEvent<
      TokensSoldEvent.InputTuple,
      TokensSoldEvent.OutputTuple,
      TokensSoldEvent.OutputObject
    >;
  };
}
